.TH MINITIMER 1 minitimer\-VERSION
.SH NAME
.PP
minitimer \- A timer in your terminal
.SH SYNOPSIS
.PP
.B minitimer
.RB [ \-lsv ]
.RB [ \-L
.IR label ]
.RI [ timecode ]
.SH DESCRIPTION
.PP
.B minitimer 
is a very simple timer that lives in the terminal of your system. 
It supports pausing and resuming the countdown.
.PP
.B minitimer 
is started by passing
.I timecode 
in HH:MM:SS format (for example, 01:10:10 for 1 hour, 10 mins., 10 secs.).
.PP
There are two indicators that are also present during execution:
.TP
.B *
If set, the timer is running.
.TP
.B +
If set, the time shown is a lap.
.PP
A label may be set using the
.I \-L
option.
This label is shown after the timer, separated by a tab character
(configurable in
.IR config.h ).
.SS Commands
During execution, pressing these keys will perform an action:
.TP
.B p
Pause/resume.
.TP
.B l
Show/discard lap.
.TP
.B +
Increment the countdown by 10 secs. 
(amount configurable in the source file
.IR config.h )
.TP
.B q
Quit 
.BR minitimer .
.SH OPTIONS
.TP 
.B \-l
Switch output to a new line for every second.
.TP
.BI \-L " label"
Set up 
.I label 
to name the timer.
.TP
.B \-s
Switch to stopwatch mode (counting time up), 
from the 
.I timecode 
provided at the command line (00:00:00 by default).
.TP
.B \-v
Show version information and exit.
.SH EXIT STATUS
Upon successful execution
.B minitimer
returns 0 as its exit status.
Otherwise, an exit status greater than zero is returned.
.SH FILES
.TP 
.I /tmp/minitimer.$PID
Default location 
(configurable in source file
.IR config.h )
for a named pipe created on startup, 
where
.I $PID
refers to the PID of a running instance of 
.B minitimer. 
This named pipe accepts all interactive commands detailed above.
.SH SEE ALSO
.PP
.BR pidof (1)
